fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#
# Account.
#
ccdn_user_user_account_show:
    pattern: /{_locale}/user/my/account
    defaults: { _controller: CCDNUserUserBundle:Account:show }

ccdn_user_user_account_edit:
    pattern: /{_locale}/user/my/account/edit
    defaults: { _controller: CCDNUserUserBundle:Account:edit }

fos_user_profile_show:
    pattern: /{_locale}/user/my/account
    defaults: { _controller: CCDNUserUserBundle:Account:show, userId: 0 }

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#
# Registration.
#
ccdn_user_user_registration_terms:
    pattern: /{_locale}/register/terms
    defaults: { _controller:FOSUserBundle:Registration:registerTerms, _locale: en }

fos_user_registration_register:
    pattern: /{_locale}/register
    defaults: { _controller:FOSUserBundle:Registration:register, _locale: en }

fos_user_registration_check_email:
    pattern: /{_locale}/register/check-email
    defaults: { _controller:FOSUserBundle:Registration:checkEmail, _locale: en }
    requirements:
        _method: GET

fos_user_registration_confirm:
    pattern: /{_locale}/register/confirm/{token}
    defaults: { _controller:FOSUserBundle:Registration:confirm, _locale: en }
    requirements:
        _method: GET

fos_user_registration_confirmed:
    pattern: /{_locale}/register/confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed, _locale: en }
    requirements:
        _method: GET

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /



#
# Legal Documents
#
ccdn_user_user_legal_copyright_notice:
    pattern: /{_locale}/user/legal/copyright_notice
    defaults: { _controller: CCDNUserUserBundle:Legal:showCopyrightNotice, _locale: en }

ccdn_user_user_legal_disclaimer:
    pattern: /{_locale}/user/legal/disclaimer
    defaults: { _controller: CCDNUserUserBundle:Legal:showDisclaimer, _locale: en }

ccdn_user_user_legal_privacy_policy:
    pattern: /{_locale}/user/legal/privacy_policy
    defaults: { _controller: CCDNUserUserBundle:Legal:showPrivacyPolicy, _locale: en }

ccdn_user_user_legal_terms_conditions:
    pattern: /{_locale}/user/legal/terms_and_conditions
    defaults: { _controller: CCDNUserUserBundle:Legal:showTermsConditions, _locale: en }
