parameters:

    # Service Parameters defined in app/config

services:

    #
    # Repositories.
    #
    ccdn_user_user.repository.user:
        class: %ccdn_user_user.repository.user.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ccdn_user_user.entity.user.class%

    #
    # Registration Forms.
    #
    ccdn_user_user.form.type.registration:
        class: %ccdn_user_user.form.type.registration.class%
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: ccdn_user_registration }

    #
    # Dashboard Integrator.
    #
    ccdn_user_user.component.dashboard.integrator:
        class: %ccdn_user_user.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }

    #
    # Route Referer.
    #
    ccdn_user_user.component.route_referer_ignore.list:
        class: %ccdn_user_user.component.route_referer_ignore.list.class%
        tags:
            - { name: ccdn_user_security.route_referer_ignore }
